### PR TITLE
Support files added

### PR DESCRIPTION
**Pull request by leigh-pointer**
Added cmd file for build support
Added nuspec for the nuGet package creation

### CODE REVIEW

**Comment by sbwalker** [comment]
@leigh-pointer do you think the the cmd and nuspec files should be in the Oqtane.Client folder? When I created then yesterday for de-DE I put them in the Resources folder ( with all of the paths relative to that folder ). My thought was that when someone copied the contents of the Resources folder to their Oqtane framework instance it would include these files to make it simpler to generate the nupkg.

**Comment by leigh-pointer** [comment]
@sbwalker I cant see there being an issue and if you are to put them somewhere it is a good a place as any.  My only concern is that the SharedResources.resx files get maintained in the Resources folder.

**Comment by sbwalker** [comment]
@leigh-pointer I am trying to make the instructions more clear for people who want to use the translations - does this diagram make sense:

https://github.com/oqtane/oqtane.translations/blob/main/README.md

**Comment by leigh-pointer** [comment]
@sbwalker I think it is clear enough. The diagram makes is clear by example, which is always good.

**Pull request merged**
