### PR TITLE
Added Persian Language

### PR DESCRIPTION
**Pull request by ajahangard**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/oqtane/oqtane.translations?pullRequest=15) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/oqtane/oqtane.translations?pullRequest=15) before we can accept your contribution.<br/><br/>:x: ajahangard [sign now](https://cla.dotnetfoundation.org/oqtane/oqtane.translations?pullRequest=15)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/oqtane/oqtane.translations?pullRequest=15) it.</sub>

**Comment by hishamco** [comment]
Thanks @ajahangard, but AFAIK Persian uses `fa-IR` Am I right?

**Comment by ajahangard** [comment]
> Thanks @ajahangard, but AFAIK Persian uses `fa-IR` Am I right?

`fa` is the general code for Persian and `fa-IR` is for Persian(Iran), like `ar` and `ar-SA`.
if it is a requirement I can change file names.

**Comment by hishamco** [comment]
Ya, I know it's general ;) but I'm not sure if any other than Iran use `fa`

**Comment by hishamco** [comment]
If it's YES, please revert your last commit

Thanks

**Comment by ajahangard** [comment]
> If it's YES, please revert your last commit
> 
> Thanks

I checked and I chose to use `fa-IR` rather than `fa`. so I changed the files and committed the changes. Should I so anything else?

**Comment by ajahangard** [comment]
I reverted my commits and recommitted the correct culture files.

**Pull request merged**
