### PR TITLE
Spanish/Español Language Support

### PR DESCRIPTION
**Pull request by elgransan**
* Spanish/Español Language Support

### CODE REVIEW

**Comment by hishamco** [comment]
Great!! could you please do two things:

- Use `Spanish (es) instead of native name
- Locate the resources into `Oqtane.Client\Resource` so they could be easier to copy into the Oqtane app (refer to the commit https://github.com/oqtane/oqtane.translations/commit/b1ecd8ea3122707751f85f96c27bea12955a1735)

**Comment by hishamco** [comment]
Why you closed the PR, you can do what I asked for, then add new commits

**Comment by elgransan** [comment]
Sorry I didn't know, I created a new one

**Comment by elgransan** [comment]
Sorry I'm not allowed to reopen

**Comment by hishamco** [comment]
The, start I new PR

**Pull request closed without merging**
