### PR TITLE
Release 2.3.1

### PR DESCRIPTION
**Pull request by ijaz-saeed**

### CODE REVIEW

**Comment by ijaz-saeed** [comment]
@sbwalker , @hishamco , please review and merge, thanks

**Comment by hishamco** [comment]
@sbwalker are we still maintaine the localization here or we need to upload it to Oqtane.org?

**Comment by sbwalker** [comment]
The Package Registry (https://www.oqtane.net) is only used for registering extensions ie. modules, themes, translations. However nothing is actually uploaded to the Registry. Extensions must be packaged as Nuget packages (*.nupkg) and uploaded to a public package repository. Currently the only supported package repository is Nuget.org - however I will soon be adding support for GitHub as well.

**Comment by sbwalker** [comment]
So to answer your question... the source translation files should still be maintained in this repo. And soon you will be able to upload the Nuget package to this repo as well and link to it in the Registry.

**Pull request merged**
