### PR TITLE
Release 2.2.0  Urdu translations

### PR DESCRIPTION
**Pull request by ijaz-saeed**

### CODE REVIEW

**Comment by sbwalker** [comment]
Can you please add a readme file similar to the Dutch or German folders to identify translation metadata ( ie. the Oqtane version that these resx files relate to )

**Comment by ijaz-saeed** [comment]
> Can you please add a readme file similar to the Dutch or German folders to identify translation metadata ( ie. the Oqtane version that these resx files relate to )

added, please verify, thanks

**Comment by hishamco** [comment]
Seems no one notice the changes, I will review then merge if there's no comment

**Review by hishamco — CHANGES_REQUESTED** [review]
Could you please follow https://github.com/oqtane/oqtane.translations/tree/main/Netherlands%20(nl-NL), by adding a readme file and target a specific framework, then I can merge?

**Comment by ijaz-saeed** [comment]
> Could you please follow https://github.com/oqtane/oqtane.translations/tree/main/Netherlands%20(nl-NL), by adding a readme file and target a specific framework, then I can merge?

hi, 
@hishamco thanks for noticing the PR and yes the read-me is already the part of my PR, here it is, https://github.com/ijaz-saeed/oqtane.translations/tree/main/Urdu%20(ur-PK)

**Comment by hishamco** [comment]
You are right seems the missing part is a framework target

**Comment by ijaz-saeed** [comment]
hi @hishamco , 
sorry I could not get the "missing framework target" , can u please explain more. here is the screenshot of my read-me, framework target is not there ? 
image

**Comment by hishamco** [comment]
I didn't mean the README file, the actual change, Please refer to the Netherland link that I mentioned

@sbwalker what was your plan to differentiate between the translations for each version?

**Comment by ijaz-saeed** [comment]
hi @hishamco by following the Netherland link, I have added the missing files, please check. thanks

**Comment by hishamco** [comment]
Thanks a lot Ijaz

**Pull request merged**
