### PR TITLE
Add portuguese (Portugal) translations

### PR DESCRIPTION
**Pull request by pcancela**
@hishamco here are the (pt-PT) translations. 

During local testing I noticed that there are a lot of missing parts that weren't translated due to the fact that they do not exist on the original english folder. Is this a known issue?

Cheers!

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/oqtane/oqtane.translations?pullRequest=6) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/oqtane/oqtane.translations?pullRequest=6) before we can accept your contribution.<br/><br/>:x: pcancela [sign now](https://cla.dotnetfoundation.org/oqtane/oqtane.translations?pullRequest=6)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/oqtane/oqtane.translations?pullRequest=6) it.</sub>

**Comment by hishamco** [comment]
Thanks @pcancela for your initiative work, I will try to quick review your changes. 

> During local testing I noticed that there are a lot of missing parts that weren't translated due to the fact that they do not exist on the original english folder. Is this a known issue?

In case there are issues or missing translations, please let me know if it's from the extractor tool https://github.com/hishamco/Oqtane.ResxExtractor if it's yes you can report them directly in its repo, otherwise report them in Oqtane repo and I will take care about them

Thanks

**Comment by hishamco** [comment]
BTW please let us know if you have a feedback about the documented instructions, you can refer to this [link](https://github.com/oqtane/oqtane.translations/discussions/2#discussioncomment-515842) for some questions that will help us to improve our instructions

**Review by hishamco — APPROVED** [review]
LGTM

**Pull request merged**
