### PR TITLE
Add Vietnamese language

### PR DESCRIPTION
**Pull request by lthoa**

### CODE REVIEW

**Comment by hishamco** [comment]
Thanks @lthoa I will have a look ...

**Comment by elgransan** [comment]
image

I think this 2 files (and all the .vs folder) must be excluded from the project

**Comment by hishamco** [comment]
This folder related to the environment itself, no longer needed

**Comment by hishamco** [comment]
Done in https://github.com/oqtane/oqtane.translations/commit/a46a3f5a806052d5fc8d69eed0e72e7f950ccada

Thanks @elgransan

**Comment by hishamco** [comment]
@lthoa could please add culture code before `resx` extension to Vietnamse resources?

**Pull request merged**
