### PR TITLE
New Resx Additions

### PR DESCRIPTION
**Pull request by leigh-pointer**

### CODE REVIEW

**Comment by hishamco** [comment]
Are these added by you or the tools, coz the Oqtane Resx extractor need some work to cover some other resources

**Comment by leigh-pointer** [comment]
It was a bit of both.

**Comment by hishamco** [comment]
Please keep the once that generated by the tool in this PR, I am planning to update the tool to discover more resources.  If you want to do that please send a PR

Thanks

**Comment by leigh-pointer** [comment]
@hishamco sorry , what I mean is that the files were created by the app but I updated the data in different ways.  So in short all files in this PR are generated from the tool.

**Comment by hishamco** [comment]
No problem I will merge the PR, I said that to avoid overwrite your changes whenever I update the tool

Thanks

**Pull request merged**
